/*
 * HERB Compiled Runtime
 * Generated by herb_compiler.py
 *
 * This is a standalone C program that implements a HERB fact store
 * with derivation rules compiled to native loops.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>

#define INITIAL_CAPACITY 1024
#define HASH_TABLE_SIZE 4096


/* Symbol Table (for debugging) */
/* 0: "entity_0" */
/* 1: "is_a" */
/* 2: "person" */
/* 3: "location" */
/* 4: "zone_0" */
/* 5: "entity_1" */
/* 6: "zone_1" */
/* 7: "entity_2" */
/* 8: "zone_2" */
/* 9: "entity_3" */
/* 10: "zone_3" */
/* 11: "entity_4" */
/* 12: "zone_4" */
/* 13: "entity_5" */
/* 14: "zone_5" */
/* 15: "entity_6" */
/* 16: "zone_6" */
/* 17: "entity_7" */
/* 18: "zone_7" */
/* 19: "entity_8" */
/* 20: "zone_8" */
/* 21: "entity_9" */
/* 22: "zone_9" */
/* 23: "entity_10" */
/* 24: "entity_11" */
/* 25: "entity_12" */
/* 26: "entity_13" */
/* 27: "entity_14" */
/* 28: "entity_15" */
/* 29: "entity_16" */
/* 30: "entity_17" */
/* 31: "entity_18" */
/* 32: "entity_19" */
/* 33: "entity_20" */
/* 34: "entity_21" */
/* 35: "entity_22" */
/* 36: "entity_23" */
/* 37: "entity_24" */
/* 38: "entity_25" */
/* 39: "entity_26" */
/* 40: "entity_27" */
/* 41: "entity_28" */
/* 42: "entity_29" */
/* 43: "entity_30" */
/* 44: "entity_31" */
/* 45: "entity_32" */
/* 46: "entity_33" */
/* 47: "entity_34" */
/* 48: "entity_35" */
/* 49: "entity_36" */
/* 50: "entity_37" */
/* 51: "entity_38" */
/* 52: "entity_39" */
/* 53: "entity_40" */
/* 54: "entity_41" */
/* 55: "entity_42" */
/* 56: "entity_43" */
/* 57: "entity_44" */
/* 58: "entity_45" */
/* 59: "entity_46" */
/* 60: "entity_47" */
/* 61: "entity_48" */
/* 62: "entity_49" */
/* 63: "entity_50" */
/* 64: "entity_51" */
/* 65: "entity_52" */
/* 66: "entity_53" */
/* 67: "entity_54" */
/* 68: "entity_55" */
/* 69: "entity_56" */
/* 70: "entity_57" */
/* 71: "entity_58" */
/* 72: "entity_59" */
/* 73: "entity_60" */
/* 74: "entity_61" */
/* 75: "entity_62" */
/* 76: "entity_63" */
/* 77: "entity_64" */
/* 78: "entity_65" */
/* 79: "entity_66" */
/* 80: "entity_67" */
/* 81: "entity_68" */
/* 82: "entity_69" */
/* 83: "entity_70" */
/* 84: "entity_71" */
/* 85: "entity_72" */
/* 86: "entity_73" */
/* 87: "entity_74" */
/* 88: "entity_75" */
/* 89: "entity_76" */
/* 90: "entity_77" */
/* 91: "entity_78" */
/* 92: "entity_79" */
/* 93: "entity_80" */
/* 94: "entity_81" */
/* 95: "entity_82" */
/* 96: "entity_83" */
/* 97: "entity_84" */
/* 98: "entity_85" */
/* 99: "entity_86" */
/* 100: "entity_87" */
/* 101: "entity_88" */
/* 102: "entity_89" */
/* 103: "entity_90" */
/* 104: "entity_91" */
/* 105: "entity_92" */
/* 106: "entity_93" */
/* 107: "entity_94" */
/* 108: "entity_95" */
/* 109: "entity_96" */
/* 110: "entity_97" */
/* 111: "entity_98" */
/* 112: "entity_99" */
/* 113: "visibility" */
/* 114: "derivation_rule" */
/* 115: "pattern_count" */
/* 116: "4" */
/* 117: "sees" */

/* ============================================================
 * DATA STRUCTURES
 * ============================================================ */

typedef struct {
    int subject;
    int relation;
    int object;
} Fact;

typedef struct {
    Fact* facts;
    int count;
    int capacity;

    /* Indices: arrays of fact indices, organized by hash */
    int* by_sro;      /* Hash(s,r,o) -> fact index or -1 */
    int* by_sr;       /* Hash(s,r) -> linked list head, -1 if empty */
    int* by_ro;       /* Hash(r,o) -> linked list head, -1 if empty */
    int* sr_next;     /* next pointer for (s,r) chain */
    int* ro_next;     /* next pointer for (r,o) chain */
} FactStore;


/* ============================================================
 * HASH FUNCTIONS
 * ============================================================ */

static inline uint32_t hash_combine(uint32_t a, uint32_t b) {
    /* FNV-1a style combination */
    return (a * 16777619) ^ b;
}

static inline uint32_t hash_triple(int s, int r, int o) {
    uint32_t h = 2166136261u;
    h = hash_combine(h, (uint32_t)s);
    h = hash_combine(h, (uint32_t)r);
    h = hash_combine(h, (uint32_t)o);
    return h % HASH_TABLE_SIZE;
}

static inline uint32_t hash_pair_sr(int s, int r) {
    uint32_t h = 2166136261u;
    h = hash_combine(h, (uint32_t)s);
    h = hash_combine(h, (uint32_t)r);
    return h % HASH_TABLE_SIZE;
}

static inline uint32_t hash_pair_ro(int r, int o) {
    uint32_t h = 2166136261u;
    h = hash_combine(h, (uint32_t)r);
    h = hash_combine(h, (uint32_t)o);
    return h % HASH_TABLE_SIZE;
}


/* ============================================================
 * FACT STORE OPERATIONS
 * ============================================================ */

FactStore* factstore_new() {
    FactStore* store = malloc(sizeof(FactStore));
    store->capacity = INITIAL_CAPACITY;
    store->count = 0;
    store->facts = malloc(sizeof(Fact) * store->capacity);

    store->by_sro = malloc(sizeof(int) * HASH_TABLE_SIZE);
    store->by_sr = malloc(sizeof(int) * HASH_TABLE_SIZE);
    store->by_ro = malloc(sizeof(int) * HASH_TABLE_SIZE);
    store->sr_next = malloc(sizeof(int) * store->capacity);
    store->ro_next = malloc(sizeof(int) * store->capacity);

    for (int i = 0; i < HASH_TABLE_SIZE; i++) {
        store->by_sro[i] = -1;
        store->by_sr[i] = -1;
        store->by_ro[i] = -1;
    }

    return store;
}

void factstore_free(FactStore* store) {
    free(store->facts);
    free(store->by_sro);
    free(store->by_sr);
    free(store->by_ro);
    free(store->sr_next);
    free(store->ro_next);
    free(store);
}

/* Check if fact exists using SRO index */
int factstore_exists(FactStore* store, int s, int r, int o) {
    uint32_t h = hash_triple(s, r, o);
    int idx = store->by_sro[h];

    /* Linear probing for collisions */
    int probes = 0;
    while (idx >= 0 && probes < HASH_TABLE_SIZE) {
        Fact* f = &store->facts[idx];
        if (f->subject == s && f->relation == r && f->object == o) {
            return 1;
        }
        h = (h + 1) % HASH_TABLE_SIZE;
        idx = store->by_sro[h];
        probes++;
    }
    return 0;
}

/* Assert a new fact. Returns 1 if new, 0 if already exists. */
int factstore_assert(FactStore* store, int s, int r, int o) {
    /* Check if already exists */
    if (factstore_exists(store, s, r, o)) {
        return 0;
    }

    /* Grow if needed */
    if (store->count >= store->capacity) {
        store->capacity *= 2;
        store->facts = realloc(store->facts, sizeof(Fact) * store->capacity);
        store->sr_next = realloc(store->sr_next, sizeof(int) * store->capacity);
        store->ro_next = realloc(store->ro_next, sizeof(int) * store->capacity);
    }

    /* Add fact */
    int idx = store->count++;
    store->facts[idx].subject = s;
    store->facts[idx].relation = r;
    store->facts[idx].object = o;

    /* Update SRO index (linear probing) */
    uint32_t h = hash_triple(s, r, o);
    while (store->by_sro[h] >= 0) {
        h = (h + 1) % HASH_TABLE_SIZE;
    }
    store->by_sro[h] = idx;

    /* Update SR index (linked list) */
    uint32_t hsr = hash_pair_sr(s, r);
    store->sr_next[idx] = store->by_sr[hsr];
    store->by_sr[hsr] = idx;

    /* Update RO index (linked list) */
    uint32_t hro = hash_pair_ro(r, o);
    store->ro_next[idx] = store->by_ro[hro];
    store->by_ro[hro] = idx;

    return 1;
}

/* Print all facts */
void factstore_print(FactStore* store, const char** symbols, int symbol_count) {
    printf("=== Fact Store (%d facts) ===\n", store->count);
    for (int i = 0; i < store->count; i++) {
        Fact* f = &store->facts[i];
        const char* s_str = (f->subject < symbol_count) ? symbols[f->subject] : "?";
        const char* r_str = (f->relation < symbol_count) ? symbols[f->relation] : "?";
        const char* o_str = (f->object < symbol_count) ? symbols[f->object] : "?";
        printf("  (%s %s %s)\n", s_str, r_str, o_str);
    }
}


/* Rule: visibility */
int rule_visibility(FactStore* store) {
    int derived = 0;
    /* Pattern 0: (?, 1, 2) using RO index */
    int idx_0 = store->by_ro[hash_pair_ro(1, 2)];
    while (idx_0 >= 0) {
        Fact* f0 = &store->facts[idx_0];
        if (f0->relation == 1 && f0->object == 2) {
            int x = f0->subject;
            /* Pattern 1: (?, 1, 2) using RO index */
            int idx_1 = store->by_ro[hash_pair_ro(1, 2)];
            while (idx_1 >= 0) {
                Fact* f1 = &store->facts[idx_1];
                if (f1->relation == 1 && f1->object == 2) {
                    int y = f1->subject;
                    /* Pattern 2: (bound:x, 3, ?) using SR index */
                    int idx_2 = store->by_sr[hash_pair_sr(x, 3)];
                    while (idx_2 >= 0) {
                        Fact* f2 = &store->facts[idx_2];
                        if (f2->subject == x && f2->relation == 3) {
                            int z = f2->object;
                            /* Pattern 3: (bound:y, 3, ?) using SR index */
                            int idx_3 = store->by_sr[hash_pair_sr(y, 3)];
                            while (idx_3 >= 0) {
                                Fact* f3 = &store->facts[idx_3];
                                if (f3->subject == y && f3->relation == 3 && f3->object == z) {
                                    /* Assert template */
                                    derived += factstore_assert(store, x, 117, y);
                                }
                                idx_3 = store->sr_next[idx_3];
                            }
                        }
                        idx_2 = store->sr_next[idx_2];
                    }
                }
                idx_1 = store->ro_next[idx_1];
            }
        }
        idx_0 = store->ro_next[idx_0];
    }
    return derived;
}

/* ============================================================
 * DERIVATION (FIXPOINT LOOP)
 * ============================================================ */

int derive_to_fixpoint(FactStore* store, int max_iterations) {
    int total_derived = 0;
    int iteration = 0;

    while (iteration < max_iterations) {
        int derived = 0;
        derived += rule_visibility(store);

        if (derived == 0) {
            break;  /* Fixpoint reached */
        }
        total_derived += derived;
        iteration++;
    }

    return total_derived;
}


/* ============================================================
 * MAIN
 * ============================================================ */

/* Symbol table for printing */
const char* symbols[] = {
    "entity_0",
    "is_a",
    "person",
    "location",
    "zone_0",
    "entity_1",
    "zone_1",
    "entity_2",
    "zone_2",
    "entity_3",
    "zone_3",
    "entity_4",
    "zone_4",
    "entity_5",
    "zone_5",
    "entity_6",
    "zone_6",
    "entity_7",
    "zone_7",
    "entity_8",
    "zone_8",
    "entity_9",
    "zone_9",
    "entity_10",
    "entity_11",
    "entity_12",
    "entity_13",
    "entity_14",
    "entity_15",
    "entity_16",
    "entity_17",
    "entity_18",
    "entity_19",
    "entity_20",
    "entity_21",
    "entity_22",
    "entity_23",
    "entity_24",
    "entity_25",
    "entity_26",
    "entity_27",
    "entity_28",
    "entity_29",
    "entity_30",
    "entity_31",
    "entity_32",
    "entity_33",
    "entity_34",
    "entity_35",
    "entity_36",
    "entity_37",
    "entity_38",
    "entity_39",
    "entity_40",
    "entity_41",
    "entity_42",
    "entity_43",
    "entity_44",
    "entity_45",
    "entity_46",
    "entity_47",
    "entity_48",
    "entity_49",
    "entity_50",
    "entity_51",
    "entity_52",
    "entity_53",
    "entity_54",
    "entity_55",
    "entity_56",
    "entity_57",
    "entity_58",
    "entity_59",
    "entity_60",
    "entity_61",
    "entity_62",
    "entity_63",
    "entity_64",
    "entity_65",
    "entity_66",
    "entity_67",
    "entity_68",
    "entity_69",
    "entity_70",
    "entity_71",
    "entity_72",
    "entity_73",
    "entity_74",
    "entity_75",
    "entity_76",
    "entity_77",
    "entity_78",
    "entity_79",
    "entity_80",
    "entity_81",
    "entity_82",
    "entity_83",
    "entity_84",
    "entity_85",
    "entity_86",
    "entity_87",
    "entity_88",
    "entity_89",
    "entity_90",
    "entity_91",
    "entity_92",
    "entity_93",
    "entity_94",
    "entity_95",
    "entity_96",
    "entity_97",
    "entity_98",
    "entity_99",
    "visibility",
    "derivation_rule",
    "pattern_count",
    "4",
    "sees"
};

int main() {
    printf("HERB Compiled Runtime\n");
    printf("======================\n\n");

    /* Create fact store */
    FactStore* store = factstore_new();

    /* Assert initial facts */
    printf("Asserting initial facts...\n");
    factstore_assert(store, 0, 1, 2);
    factstore_assert(store, 0, 3, 4);
    factstore_assert(store, 5, 1, 2);
    factstore_assert(store, 5, 3, 6);
    factstore_assert(store, 7, 1, 2);
    factstore_assert(store, 7, 3, 8);
    factstore_assert(store, 9, 1, 2);
    factstore_assert(store, 9, 3, 10);
    factstore_assert(store, 11, 1, 2);
    factstore_assert(store, 11, 3, 12);
    factstore_assert(store, 13, 1, 2);
    factstore_assert(store, 13, 3, 14);
    factstore_assert(store, 15, 1, 2);
    factstore_assert(store, 15, 3, 16);
    factstore_assert(store, 17, 1, 2);
    factstore_assert(store, 17, 3, 18);
    factstore_assert(store, 19, 1, 2);
    factstore_assert(store, 19, 3, 20);
    factstore_assert(store, 21, 1, 2);
    factstore_assert(store, 21, 3, 22);
    factstore_assert(store, 23, 1, 2);
    factstore_assert(store, 23, 3, 4);
    factstore_assert(store, 24, 1, 2);
    factstore_assert(store, 24, 3, 6);
    factstore_assert(store, 25, 1, 2);
    factstore_assert(store, 25, 3, 8);
    factstore_assert(store, 26, 1, 2);
    factstore_assert(store, 26, 3, 10);
    factstore_assert(store, 27, 1, 2);
    factstore_assert(store, 27, 3, 12);
    factstore_assert(store, 28, 1, 2);
    factstore_assert(store, 28, 3, 14);
    factstore_assert(store, 29, 1, 2);
    factstore_assert(store, 29, 3, 16);
    factstore_assert(store, 30, 1, 2);
    factstore_assert(store, 30, 3, 18);
    factstore_assert(store, 31, 1, 2);
    factstore_assert(store, 31, 3, 20);
    factstore_assert(store, 32, 1, 2);
    factstore_assert(store, 32, 3, 22);
    factstore_assert(store, 33, 1, 2);
    factstore_assert(store, 33, 3, 4);
    factstore_assert(store, 34, 1, 2);
    factstore_assert(store, 34, 3, 6);
    factstore_assert(store, 35, 1, 2);
    factstore_assert(store, 35, 3, 8);
    factstore_assert(store, 36, 1, 2);
    factstore_assert(store, 36, 3, 10);
    factstore_assert(store, 37, 1, 2);
    factstore_assert(store, 37, 3, 12);
    factstore_assert(store, 38, 1, 2);
    factstore_assert(store, 38, 3, 14);
    factstore_assert(store, 39, 1, 2);
    factstore_assert(store, 39, 3, 16);
    factstore_assert(store, 40, 1, 2);
    factstore_assert(store, 40, 3, 18);
    factstore_assert(store, 41, 1, 2);
    factstore_assert(store, 41, 3, 20);
    factstore_assert(store, 42, 1, 2);
    factstore_assert(store, 42, 3, 22);
    factstore_assert(store, 43, 1, 2);
    factstore_assert(store, 43, 3, 4);
    factstore_assert(store, 44, 1, 2);
    factstore_assert(store, 44, 3, 6);
    factstore_assert(store, 45, 1, 2);
    factstore_assert(store, 45, 3, 8);
    factstore_assert(store, 46, 1, 2);
    factstore_assert(store, 46, 3, 10);
    factstore_assert(store, 47, 1, 2);
    factstore_assert(store, 47, 3, 12);
    factstore_assert(store, 48, 1, 2);
    factstore_assert(store, 48, 3, 14);
    factstore_assert(store, 49, 1, 2);
    factstore_assert(store, 49, 3, 16);
    factstore_assert(store, 50, 1, 2);
    factstore_assert(store, 50, 3, 18);
    factstore_assert(store, 51, 1, 2);
    factstore_assert(store, 51, 3, 20);
    factstore_assert(store, 52, 1, 2);
    factstore_assert(store, 52, 3, 22);
    factstore_assert(store, 53, 1, 2);
    factstore_assert(store, 53, 3, 4);
    factstore_assert(store, 54, 1, 2);
    factstore_assert(store, 54, 3, 6);
    factstore_assert(store, 55, 1, 2);
    factstore_assert(store, 55, 3, 8);
    factstore_assert(store, 56, 1, 2);
    factstore_assert(store, 56, 3, 10);
    factstore_assert(store, 57, 1, 2);
    factstore_assert(store, 57, 3, 12);
    factstore_assert(store, 58, 1, 2);
    factstore_assert(store, 58, 3, 14);
    factstore_assert(store, 59, 1, 2);
    factstore_assert(store, 59, 3, 16);
    factstore_assert(store, 60, 1, 2);
    factstore_assert(store, 60, 3, 18);
    factstore_assert(store, 61, 1, 2);
    factstore_assert(store, 61, 3, 20);
    factstore_assert(store, 62, 1, 2);
    factstore_assert(store, 62, 3, 22);
    factstore_assert(store, 63, 1, 2);
    factstore_assert(store, 63, 3, 4);
    factstore_assert(store, 64, 1, 2);
    factstore_assert(store, 64, 3, 6);
    factstore_assert(store, 65, 1, 2);
    factstore_assert(store, 65, 3, 8);
    factstore_assert(store, 66, 1, 2);
    factstore_assert(store, 66, 3, 10);
    factstore_assert(store, 67, 1, 2);
    factstore_assert(store, 67, 3, 12);
    factstore_assert(store, 68, 1, 2);
    factstore_assert(store, 68, 3, 14);
    factstore_assert(store, 69, 1, 2);
    factstore_assert(store, 69, 3, 16);
    factstore_assert(store, 70, 1, 2);
    factstore_assert(store, 70, 3, 18);
    factstore_assert(store, 71, 1, 2);
    factstore_assert(store, 71, 3, 20);
    factstore_assert(store, 72, 1, 2);
    factstore_assert(store, 72, 3, 22);
    factstore_assert(store, 73, 1, 2);
    factstore_assert(store, 73, 3, 4);
    factstore_assert(store, 74, 1, 2);
    factstore_assert(store, 74, 3, 6);
    factstore_assert(store, 75, 1, 2);
    factstore_assert(store, 75, 3, 8);
    factstore_assert(store, 76, 1, 2);
    factstore_assert(store, 76, 3, 10);
    factstore_assert(store, 77, 1, 2);
    factstore_assert(store, 77, 3, 12);
    factstore_assert(store, 78, 1, 2);
    factstore_assert(store, 78, 3, 14);
    factstore_assert(store, 79, 1, 2);
    factstore_assert(store, 79, 3, 16);
    factstore_assert(store, 80, 1, 2);
    factstore_assert(store, 80, 3, 18);
    factstore_assert(store, 81, 1, 2);
    factstore_assert(store, 81, 3, 20);
    factstore_assert(store, 82, 1, 2);
    factstore_assert(store, 82, 3, 22);
    factstore_assert(store, 83, 1, 2);
    factstore_assert(store, 83, 3, 4);
    factstore_assert(store, 84, 1, 2);
    factstore_assert(store, 84, 3, 6);
    factstore_assert(store, 85, 1, 2);
    factstore_assert(store, 85, 3, 8);
    factstore_assert(store, 86, 1, 2);
    factstore_assert(store, 86, 3, 10);
    factstore_assert(store, 87, 1, 2);
    factstore_assert(store, 87, 3, 12);
    factstore_assert(store, 88, 1, 2);
    factstore_assert(store, 88, 3, 14);
    factstore_assert(store, 89, 1, 2);
    factstore_assert(store, 89, 3, 16);
    factstore_assert(store, 90, 1, 2);
    factstore_assert(store, 90, 3, 18);
    factstore_assert(store, 91, 1, 2);
    factstore_assert(store, 91, 3, 20);
    factstore_assert(store, 92, 1, 2);
    factstore_assert(store, 92, 3, 22);
    factstore_assert(store, 93, 1, 2);
    factstore_assert(store, 93, 3, 4);
    factstore_assert(store, 94, 1, 2);
    factstore_assert(store, 94, 3, 6);
    factstore_assert(store, 95, 1, 2);
    factstore_assert(store, 95, 3, 8);
    factstore_assert(store, 96, 1, 2);
    factstore_assert(store, 96, 3, 10);
    factstore_assert(store, 97, 1, 2);
    factstore_assert(store, 97, 3, 12);
    factstore_assert(store, 98, 1, 2);
    factstore_assert(store, 98, 3, 14);
    factstore_assert(store, 99, 1, 2);
    factstore_assert(store, 99, 3, 16);
    factstore_assert(store, 100, 1, 2);
    factstore_assert(store, 100, 3, 18);
    factstore_assert(store, 101, 1, 2);
    factstore_assert(store, 101, 3, 20);
    factstore_assert(store, 102, 1, 2);
    factstore_assert(store, 102, 3, 22);
    factstore_assert(store, 103, 1, 2);
    factstore_assert(store, 103, 3, 4);
    factstore_assert(store, 104, 1, 2);
    factstore_assert(store, 104, 3, 6);
    factstore_assert(store, 105, 1, 2);
    factstore_assert(store, 105, 3, 8);
    factstore_assert(store, 106, 1, 2);
    factstore_assert(store, 106, 3, 10);
    factstore_assert(store, 107, 1, 2);
    factstore_assert(store, 107, 3, 12);
    factstore_assert(store, 108, 1, 2);
    factstore_assert(store, 108, 3, 14);
    factstore_assert(store, 109, 1, 2);
    factstore_assert(store, 109, 3, 16);
    factstore_assert(store, 110, 1, 2);
    factstore_assert(store, 110, 3, 18);
    factstore_assert(store, 111, 1, 2);
    factstore_assert(store, 111, 3, 20);
    factstore_assert(store, 112, 1, 2);
    factstore_assert(store, 112, 3, 22);
    factstore_assert(store, 113, 1, 114);
    factstore_assert(store, 113, 115, 116);
    printf("Initial facts: %d\n\n", store->count);

    /* Run derivation */
    printf("Running derivation...\n");
    clock_t start = clock();
    int derived = derive_to_fixpoint(store, 1000);
    clock_t end = clock();
    double time_ms = (double)(end - start) * 1000.0 / CLOCKS_PER_SEC;

    printf("Derived %d new facts in %.3f ms\n\n", derived, time_ms);

    /* Print results */
    factstore_print(store, symbols, 118);

    /* Cleanup */
    factstore_free(store);

    return 0;
}
