"""
HERB v2: The Graph

This is the core implementation of the graph-based program representation.
The graph IS the program — there is no separate source code.

See GRAPH_REPR.md for the design specification.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Dict, List, Set, Optional, Any, Tuple as PyTuple, Union
import time


# =============================================================================
# VALUES
# =============================================================================

class ValueType(Enum):
    """The primitive value types."""
    INT = auto()
    FLOAT = auto()
    STRING = auto()
    BOOL = auto()
    ENTITY_REF = auto()
    NULL = auto()


@dataclass(frozen=True)
class Value:
    """A primitive value in the graph."""
    type: ValueType
    data: Any  # int, float, str, bool, int (entity_id), or None

    @staticmethod
    def int(n: int) -> Value:
        return Value(ValueType.INT, n)

    @staticmethod
    def float(n: float) -> Value:
        return Value(ValueType.FLOAT, n)

    @staticmethod
    def string(s: str) -> Value:
        return Value(ValueType.STRING, s)

    @staticmethod
    def bool(b: bool) -> Value:
        return Value(ValueType.BOOL, b)

    @staticmethod
    def entity_ref(entity_id: int) -> Value:
        return Value(ValueType.ENTITY_REF, entity_id)

    @staticmethod
    def null() -> Value:
        return Value(ValueType.NULL, None)

    def __repr__(self):
        if self.type == ValueType.NULL:
            return "null"
        elif self.type == ValueType.ENTITY_REF:
            return f"@{self.data}"
        elif self.type == ValueType.STRING:
            return f'"{self.data}"'
        else:
            return str(self.data)


# =============================================================================
# ENTITIES
# =============================================================================

@dataclass
class Entity:
    """
    An entity in the graph. Entities don't have properties — they participate
    in relations.
    """
    id: int
    type_id: int      # Reference to the entity type (also an entity)
    level: int        # 0=instance, 1=type, 2=meta-type, 3=system
    created_at: int   # Tick when created

    def __hash__(self):
        return hash(self.id)

    def __eq__(self, other):
        return isinstance(other, Entity) and self.id == other.id


# =============================================================================
# RELATION TYPES
# =============================================================================

@dataclass
class RoleDefinition:
    """Definition of a role in a relation type."""
    name: str
    value_type: ValueType         # What kind of value this role holds
    entity_type_id: Optional[int] # If ENTITY_REF, what type of entity (None = any)


@dataclass
class RelationType:
    """
    A relation type defines the structure of a kind of connection.
    Relation types are themselves entities (at level 2).
    """
    entity_id: int                  # The entity representing this relation type
    name: str
    roles: List[RoleDefinition]
    role_indices: Dict[str, int]    # role_name -> index for fast lookup

    def __post_init__(self):
        self.role_indices = {r.name: i for i, r in enumerate(self.roles)}

    @property
    def arity(self) -> int:
        return len(self.roles)


# =============================================================================
# TUPLES
# =============================================================================

@dataclass
class Tuple:
    """
    A tuple is an instance of a relation — a specific connection between entities.
    """
    id: int
    type_id: int              # Which RelationType
    values: List[Value]       # One value per role, in role order
    valid_from: int           # Tick when this tuple became valid
    valid_to: Optional[int]   # Tick when this tuple was retracted (None if still valid)

    def is_valid_at(self, tick: int) -> bool:
        return self.valid_from <= tick and (self.valid_to is None or tick < self.valid_to)

    def is_current(self) -> bool:
        return self.valid_to is None


# =============================================================================
# DELTAS
# =============================================================================

class DeltaKind(Enum):
    """The kinds of changes that can happen."""
    ASSERT = auto()   # Add a tuple
    RETRACT = auto()  # Remove a tuple
    MODIFY = auto()   # Change values in a tuple


class DeltaSource(Enum):
    """Where a delta originated from."""
    EXTERNAL = auto()      # From outside the system (user input, etc.)
    CONSTRAINT = auto()    # Generated by constraint maintenance
    GOAL = auto()          # Generated by goal pursuit
    DERIVED = auto()       # Generated by derived constraint propagation


class ViolationPolicy(Enum):
    """What to do when a delta violates a constraint."""
    REJECT = auto()        # Don't apply the delta
    APPLY_AND_REPAIR = auto()  # Apply, let propagation fix
    # TRANSACTION handled separately with transaction_group


@dataclass
class Delta:
    """
    A delta is a change to the graph. Deltas are the primitive — state is
    derived by applying deltas.
    """
    id: int
    kind: DeltaKind
    tuple_id: int                     # The tuple being affected
    relation_type_id: int             # Which relation type
    values: List[Value]               # The tuple values (for ASSERT) or new values (for MODIFY)
    old_values: Optional[List[Value]] # Previous values (for MODIFY/RETRACT)
    tick: int                         # When this delta occurred
    micro: int                        # Sub-tick ordering
    provenance: Provenance            # Why this delta happened


@dataclass
class Provenance:
    """Why a delta happened."""
    cause: str                        # 'external', 'derived', 'goal', 'constraint'
    source_deltas: List[int] = field(default_factory=list)  # Deltas that triggered this
    constraint_id: Optional[int] = None
    goal_id: Optional[int] = None
    description: str = ""


@dataclass
class PendingDelta:
    """
    A delta waiting to be applied during resolution.

    Pending deltas are queued rather than applied immediately, allowing:
    - Batching (multiple deltas in one resolution round)
    - Ordering by priority and causal dependencies
    - Validation before committing
    """
    # What to do
    kind: DeltaKind
    relation_type_id: int
    values: List[Value]

    # For RETRACT/MODIFY: which tuple
    tuple_id: Optional[int] = None

    # Ordering
    priority: int = 0                 # Higher = applied first
    causal_deps: List[int] = field(default_factory=list)  # Delta IDs that must be applied first

    # Metadata
    source: DeltaSource = DeltaSource.EXTERNAL
    source_constraint_id: Optional[int] = None
    source_goal_id: Optional[int] = None
    provenance: Optional[Provenance] = None

    # Violation handling
    violation_policy: ViolationPolicy = ViolationPolicy.REJECT
    transaction_group: Optional[int] = None  # For transactional semantics


class ResolutionStatus(Enum):
    """Result status of a resolution attempt."""
    QUIESCENT = auto()         # Reached stable state
    DIVERGED = auto()          # Hit iteration limit
    CONSTRAINT_VIOLATIONS = auto()  # Some constraints couldn't be satisfied


@dataclass
class ConstraintViolation:
    """Record of a constraint violation during resolution."""
    constraint_id: int
    constraint_name: str
    message: str
    trigger_delta_id: Optional[int] = None  # The delta that caused it
    failed_bindings: Optional[Dict] = None  # What bindings failed


@dataclass
class ResolutionResult:
    """The result of a resolution attempt."""
    status: ResolutionStatus
    iterations: int = 0
    applied_deltas: List[int] = field(default_factory=list)
    rejected_deltas: List[int] = field(default_factory=list)
    violations: List[ConstraintViolation] = field(default_factory=list)
    propagation_cycles: int = 0


# =============================================================================
# CONSTRAINTS (simplified for initial implementation)
# =============================================================================

class ConstraintKind(Enum):
    """Types of constraints."""
    INVARIANT = auto()
    PRECONDITION = auto()
    POSTCONDITION = auto()
    DERIVED = auto()
    MAINTENANCE = auto()


@dataclass
class Constraint:
    """
    A constraint is a condition that must hold (or should hold for goals).
    Full constraint expression language is in GRAPH_CONSTRAINTS.md.
    For now, we use Python callables as a placeholder.
    """
    entity_id: int
    name: str
    kind: ConstraintKind
    # For now: a Python function that takes (graph, context) and returns bool
    # Later: proper ConstraintExpr AST
    check_fn: Any  # Callable[[Graph, Dict], bool]
    delta_type_id: Optional[int] = None  # For preconditions/postconditions

    # For DERIVED constraints: function that computes new deltas
    # Signature: (graph, dirty_relations) -> List[PendingDelta]
    derive_fn: Any = None

    # For MAINTENANCE constraints: function that generates repair deltas
    # Signature: (graph) -> List[PendingDelta]
    repair_fn: Any = None

    # Dependencies: which relation types does this constraint read from?
    # Used for incremental checking
    depends_on_relations: List[int] = field(default_factory=list)


# =============================================================================
# PRIMORDIAL IDS
# =============================================================================

class PrimordialIds:
    """
    Fixed IDs for primordial entities. These exist in every graph.
    """
    # Level 3: System
    SYSTEM = 1
    RESOLVER = 2

    # Level 2: Meta-types
    ENTITY_TYPE = 10
    RELATION_TYPE = 11
    CONSTRAINT_TYPE = 12
    DELTA_TYPE = 13
    GOAL_TYPE = 14
    VALUE_TYPE = 15

    # Level 2: Value types
    INT = 20
    FLOAT = 21
    STRING = 22
    BOOL = 23
    ENTITY_REF = 24
    NULL_TYPE = 25

    # Level 2: Primordial relation types
    INSTANCE_OF = 30
    SUBTYPE_OF = 31
    NAME = 32
    HAS_ROLE = 33

    # First available ID for user-created entities
    FIRST_USER_ID = 100


# =============================================================================
# THE GRAPH
# =============================================================================

class Graph:
    """
    The graph IS the program. This class is the core of HERB v2.
    """

    def __init__(self):
        # Entity storage
        self.entities: Dict[int, Entity] = {}
        self.next_entity_id: int = PrimordialIds.FIRST_USER_ID

        # Relation types
        self.relation_types: Dict[int, RelationType] = {}

        # Current state (materialized tuples)
        self.tuples: Dict[int, Tuple] = {}
        self.next_tuple_id: int = 1

        # Indices
        self.tuples_by_type: Dict[int, Set[int]] = {}
        self.tuples_by_entity: Dict[int, Set[int]] = {}
        # (relation_type, role_index, value) -> set of tuple_ids
        self.tuples_by_role: Dict[PyTuple[int, int, Value], Set[int]] = {}

        # Delta log
        self.deltas: List[Delta] = []
        self.next_delta_id: int = 1
        self.current_tick: int = 0
        self.current_micro: int = 0

        # Constraints
        self.constraints: Dict[int, Constraint] = {}
        self.invariants: List[int] = []
        self.preconditions: Dict[int, List[int]] = {}   # delta_type -> constraint ids
        self.postconditions: Dict[int, List[int]] = {}  # delta_type -> constraint ids

        # Resolution state
        self.pending_deltas: List[PendingDelta] = []
        self.recently_applied: List[Delta] = []  # Deltas applied since last propagation

        # Name index (for convenience)
        self.entity_names: Dict[str, int] = {}
        self.name_by_entity: Dict[int, str] = {}

        # Initialize primordial structure
        self._init_primordial()

    def _init_primordial(self):
        """Create the primordial entities and relations."""

        # Level 3: System (self-typed)
        self._create_primordial_entity(PrimordialIds.SYSTEM, PrimordialIds.SYSTEM, 3, "SYSTEM")
        self._create_primordial_entity(PrimordialIds.RESOLVER, PrimordialIds.SYSTEM, 3, "RESOLVER")

        # Level 2: Meta-types (typed by ENTITY_TYPE, which is self-typed at this level)
        self._create_primordial_entity(PrimordialIds.ENTITY_TYPE, PrimordialIds.ENTITY_TYPE, 2, "ENTITY_TYPE")
        self._create_primordial_entity(PrimordialIds.RELATION_TYPE, PrimordialIds.ENTITY_TYPE, 2, "RELATION_TYPE")
        self._create_primordial_entity(PrimordialIds.CONSTRAINT_TYPE, PrimordialIds.ENTITY_TYPE, 2, "CONSTRAINT_TYPE")
        self._create_primordial_entity(PrimordialIds.DELTA_TYPE, PrimordialIds.ENTITY_TYPE, 2, "DELTA_TYPE")
        self._create_primordial_entity(PrimordialIds.GOAL_TYPE, PrimordialIds.ENTITY_TYPE, 2, "GOAL_TYPE")
        self._create_primordial_entity(PrimordialIds.VALUE_TYPE, PrimordialIds.ENTITY_TYPE, 2, "VALUE_TYPE")

        # Level 2: Value types (typed by VALUE_TYPE)
        self._create_primordial_entity(PrimordialIds.INT, PrimordialIds.VALUE_TYPE, 2, "INT")
        self._create_primordial_entity(PrimordialIds.FLOAT, PrimordialIds.VALUE_TYPE, 2, "FLOAT")
        self._create_primordial_entity(PrimordialIds.STRING, PrimordialIds.VALUE_TYPE, 2, "STRING")
        self._create_primordial_entity(PrimordialIds.BOOL, PrimordialIds.VALUE_TYPE, 2, "BOOL")
        self._create_primordial_entity(PrimordialIds.ENTITY_REF, PrimordialIds.VALUE_TYPE, 2, "ENTITY_REF")
        self._create_primordial_entity(PrimordialIds.NULL_TYPE, PrimordialIds.VALUE_TYPE, 2, "NULL_TYPE")

        # Primordial relation types
        self._create_primordial_relation_type(
            PrimordialIds.INSTANCE_OF, "instance_of",
            [RoleDefinition("entity", ValueType.ENTITY_REF, None),
             RoleDefinition("type", ValueType.ENTITY_REF, PrimordialIds.ENTITY_TYPE)]
        )

        self._create_primordial_relation_type(
            PrimordialIds.SUBTYPE_OF, "subtype_of",
            [RoleDefinition("subtype", ValueType.ENTITY_REF, PrimordialIds.ENTITY_TYPE),
             RoleDefinition("supertype", ValueType.ENTITY_REF, PrimordialIds.ENTITY_TYPE)]
        )

        self._create_primordial_relation_type(
            PrimordialIds.NAME, "name",
            [RoleDefinition("entity", ValueType.ENTITY_REF, None),
             RoleDefinition("name", ValueType.STRING, None)]
        )

    def _create_primordial_entity(self, entity_id: int, type_id: int, level: int, name: str):
        """Create a primordial entity (no delta logging)."""
        entity = Entity(id=entity_id, type_id=type_id, level=level, created_at=0)
        self.entities[entity_id] = entity
        self.entity_names[name] = entity_id
        self.name_by_entity[entity_id] = name

    def _create_primordial_relation_type(self, entity_id: int, name: str, roles: List[RoleDefinition]):
        """Create a primordial relation type."""
        self._create_primordial_entity(entity_id, PrimordialIds.RELATION_TYPE, 2, name)
        rel_type = RelationType(
            entity_id=entity_id,
            name=name,
            roles=roles,
            role_indices={}
        )
        rel_type.role_indices = {r.name: i for i, r in enumerate(roles)}
        self.relation_types[entity_id] = rel_type
        self.tuples_by_type[entity_id] = set()

    # =========================================================================
    # ENTITY OPERATIONS
    # =========================================================================

    def create_entity(self, type_id: int, name: Optional[str] = None, level: int = 0) -> int:
        """
        Create a new entity.

        Args:
            type_id: The type of the new entity (must exist)
            name: Optional human-readable name
            level: Entity level (0=instance, 1=type, etc.)

        Returns:
            The new entity's ID
        """
        if type_id not in self.entities:
            raise ValueError(f"Type entity {type_id} does not exist")

        entity_id = self.next_entity_id
        self.next_entity_id += 1

        entity = Entity(
            id=entity_id,
            type_id=type_id,
            level=level,
            created_at=self.current_tick
        )
        self.entities[entity_id] = entity

        if name:
            self.entity_names[name] = entity_id
            self.name_by_entity[entity_id] = name

        return entity_id

    def define_entity_type(self, name: str, parent_type_id: Optional[int] = None) -> int:
        """
        Convenience method to create a new entity type.

        Args:
            name: Name of the new type
            parent_type_id: Optional parent type (for inheritance)

        Returns:
            The new type entity's ID
        """
        type_id = self.create_entity(PrimordialIds.ENTITY_TYPE, name, level=1)

        if parent_type_id is not None:
            # Assert subtype relationship
            self.assert_tuple(PrimordialIds.SUBTYPE_OF, {
                "subtype": Value.entity_ref(type_id),
                "supertype": Value.entity_ref(parent_type_id)
            })

        return type_id

    def get_entity(self, entity_id: int) -> Optional[Entity]:
        """Get an entity by ID."""
        return self.entities.get(entity_id)

    def get_entity_by_name(self, name: str) -> Optional[int]:
        """Get an entity ID by name."""
        return self.entity_names.get(name)

    def get_name(self, entity_id: int) -> Optional[str]:
        """Get an entity's name."""
        return self.name_by_entity.get(entity_id)

    # =========================================================================
    # RELATION TYPE OPERATIONS
    # =========================================================================

    def define_relation_type(self, name: str, roles: List[PyTuple[str, ValueType, Optional[int]]]) -> int:
        """
        Create a new relation type.

        Args:
            name: Name of the relation
            roles: List of (role_name, value_type, entity_type_constraint) tuples

        Returns:
            The relation type entity's ID
        """
        entity_id = self.create_entity(PrimordialIds.RELATION_TYPE, name, level=1)

        role_defs = [
            RoleDefinition(name=r[0], value_type=r[1], entity_type_id=r[2])
            for r in roles
        ]

        rel_type = RelationType(
            entity_id=entity_id,
            name=name,
            roles=role_defs,
            role_indices={}
        )
        rel_type.role_indices = {r.name: i for i, r in enumerate(role_defs)}

        self.relation_types[entity_id] = rel_type
        self.tuples_by_type[entity_id] = set()

        return entity_id

    def get_relation_type(self, type_id: int) -> Optional[RelationType]:
        """Get a relation type by ID."""
        return self.relation_types.get(type_id)

    # =========================================================================
    # TUPLE OPERATIONS
    # =========================================================================

    def assert_tuple(self, relation_type_id: int, bindings: Dict[str, Value],
                     provenance: Optional[Provenance] = None) -> int:
        """
        Assert a new tuple (create a connection).

        Args:
            relation_type_id: The relation type
            bindings: Role name -> Value mapping
            provenance: Why this tuple is being created

        Returns:
            The new tuple's ID
        """
        rel_type = self.relation_types.get(relation_type_id)
        if rel_type is None:
            raise ValueError(f"Relation type {relation_type_id} does not exist")

        # Build values list in role order
        values = []
        for role in rel_type.roles:
            if role.name not in bindings:
                raise ValueError(f"Missing binding for role '{role.name}'")
            values.append(bindings[role.name])

        # Type check
        self._type_check_tuple(rel_type, values)

        # Create tuple
        tuple_id = self.next_tuple_id
        self.next_tuple_id += 1

        tup = Tuple(
            id=tuple_id,
            type_id=relation_type_id,
            values=values,
            valid_from=self.current_tick,
            valid_to=None
        )
        self.tuples[tuple_id] = tup

        # Update indices
        self._index_tuple(tup, add=True)

        # Create delta
        if provenance is None:
            provenance = Provenance(cause='external')

        delta = Delta(
            id=self.next_delta_id,
            kind=DeltaKind.ASSERT,
            tuple_id=tuple_id,
            relation_type_id=relation_type_id,
            values=values,
            old_values=None,
            tick=self.current_tick,
            micro=self.current_micro,
            provenance=provenance
        )
        self.next_delta_id += 1
        self.current_micro += 1
        self.deltas.append(delta)

        return tuple_id

    def retract_tuple(self, tuple_id: int, provenance: Optional[Provenance] = None):
        """
        Retract a tuple (remove a connection).

        Args:
            tuple_id: The tuple to retract
            provenance: Why this tuple is being retracted
        """
        tup = self.tuples.get(tuple_id)
        if tup is None:
            raise ValueError(f"Tuple {tuple_id} does not exist")
        if tup.valid_to is not None:
            raise ValueError(f"Tuple {tuple_id} is already retracted")

        # Mark as retracted
        tup.valid_to = self.current_tick

        # Update indices
        self._index_tuple(tup, add=False)

        # Create delta
        if provenance is None:
            provenance = Provenance(cause='external')

        delta = Delta(
            id=self.next_delta_id,
            kind=DeltaKind.RETRACT,
            tuple_id=tuple_id,
            relation_type_id=tup.type_id,
            values=tup.values,
            old_values=tup.values,
            tick=self.current_tick,
            micro=self.current_micro,
            provenance=provenance
        )
        self.next_delta_id += 1
        self.current_micro += 1
        self.deltas.append(delta)

    # =========================================================================
    # PENDING DELTA OPERATIONS (for resolution loop)
    # =========================================================================

    def queue_delta(
        self,
        kind: DeltaKind,
        relation_type_id: int,
        bindings: Dict[str, Value],
        tuple_id: Optional[int] = None,
        priority: int = 0,
        causal_deps: Optional[List[int]] = None,
        source: DeltaSource = DeltaSource.EXTERNAL,
        source_constraint_id: Optional[int] = None,
        source_goal_id: Optional[int] = None,
        violation_policy: ViolationPolicy = ViolationPolicy.REJECT,
        transaction_group: Optional[int] = None,
        provenance: Optional[Provenance] = None
    ):
        """
        Queue a delta for later application during resolution.

        Unlike assert_tuple/retract_tuple which apply immediately, this
        queues the delta to be applied during the next resolve() call.

        Args:
            kind: ASSERT, RETRACT, or MODIFY
            relation_type_id: The relation type
            bindings: Role name -> Value mapping
            tuple_id: For RETRACT/MODIFY, which tuple to affect
            priority: Higher priority deltas are applied first
            causal_deps: Delta IDs that must be applied before this one
            source: Where this delta came from
            source_constraint_id: If from a constraint, which one
            source_goal_id: If from a goal, which one
            violation_policy: What to do if constraints are violated
            transaction_group: Group ID for transactional semantics
            provenance: Explicit provenance (generated if not provided)
        """
        rel_type = self.relation_types.get(relation_type_id)
        if rel_type is None:
            raise ValueError(f"Relation type {relation_type_id} does not exist")

        # Build values list in role order
        values = []
        for role in rel_type.roles:
            if role.name not in bindings:
                raise ValueError(f"Missing binding for role '{role.name}'")
            values.append(bindings[role.name])

        # Build provenance if not provided
        if provenance is None:
            provenance = Provenance(
                cause=source.name.lower(),
                constraint_id=source_constraint_id,
                goal_id=source_goal_id
            )

        pending = PendingDelta(
            kind=kind,
            relation_type_id=relation_type_id,
            values=values,
            tuple_id=tuple_id,
            priority=priority,
            causal_deps=causal_deps or [],
            source=source,
            source_constraint_id=source_constraint_id,
            source_goal_id=source_goal_id,
            provenance=provenance,
            violation_policy=violation_policy,
            transaction_group=transaction_group
        )

        self.pending_deltas.append(pending)

    def queue_assert(
        self,
        relation_type_id: int,
        bindings: Dict[str, Value],
        **kwargs
    ):
        """Convenience: queue an ASSERT delta."""
        self.queue_delta(DeltaKind.ASSERT, relation_type_id, bindings, **kwargs)

    def queue_retract(
        self,
        relation_type_id: int,
        tuple_id: int,
        **kwargs
    ):
        """Convenience: queue a RETRACT delta."""
        rel_type = self.relation_types.get(relation_type_id)
        tup = self.tuples.get(tuple_id)
        if tup is None:
            raise ValueError(f"Tuple {tuple_id} does not exist")

        # Build bindings from tuple values
        bindings = {}
        for i, role in enumerate(rel_type.roles):
            bindings[role.name] = tup.values[i]

        self.queue_delta(
            DeltaKind.RETRACT,
            relation_type_id,
            bindings,
            tuple_id=tuple_id,
            **kwargs
        )

    def _type_check_tuple(self, rel_type: RelationType, values: List[Value]):
        """Check that values match the relation type's roles."""
        if len(values) != len(rel_type.roles):
            raise ValueError(f"Expected {len(rel_type.roles)} values, got {len(values)}")

        for role, value in zip(rel_type.roles, values):
            if value.type == ValueType.NULL:
                continue  # Null is allowed anywhere

            if role.value_type != value.type:
                raise TypeError(
                    f"Role '{role.name}' expects {role.value_type}, got {value.type}"
                )

            if role.value_type == ValueType.ENTITY_REF and role.entity_type_id is not None:
                # Check entity type constraint
                entity = self.entities.get(value.data)
                if entity is None:
                    raise ValueError(f"Entity {value.data} does not exist")
                # TODO: Check type inheritance

    def _index_tuple(self, tup: Tuple, add: bool):
        """Add or remove a tuple from indices."""
        rel_type = self.relation_types[tup.type_id]

        # By type
        if add:
            self.tuples_by_type[tup.type_id].add(tup.id)
        else:
            self.tuples_by_type[tup.type_id].discard(tup.id)

        # By entity and by role
        for i, value in enumerate(tup.values):
            if value.type == ValueType.ENTITY_REF:
                entity_id = value.data
                if add:
                    if entity_id not in self.tuples_by_entity:
                        self.tuples_by_entity[entity_id] = set()
                    self.tuples_by_entity[entity_id].add(tup.id)
                else:
                    if entity_id in self.tuples_by_entity:
                        self.tuples_by_entity[entity_id].discard(tup.id)

            # By role value
            key = (tup.type_id, i, value)
            if add:
                if key not in self.tuples_by_role:
                    self.tuples_by_role[key] = set()
                self.tuples_by_role[key].add(tup.id)
            else:
                if key in self.tuples_by_role:
                    self.tuples_by_role[key].discard(tup.id)

    # =========================================================================
    # QUERY OPERATIONS
    # =========================================================================

    def query_tuples(self, relation_type_id: int,
                     bindings: Optional[Dict[str, Value]] = None) -> List[Tuple]:
        """
        Query tuples of a relation type, optionally filtered by bindings.

        Args:
            relation_type_id: The relation type to query
            bindings: Optional partial bindings to filter by

        Returns:
            List of matching tuples (current only, not retracted)
        """
        rel_type = self.relation_types.get(relation_type_id)
        if rel_type is None:
            return []

        # Start with all tuples of this type
        tuple_ids = self.tuples_by_type.get(relation_type_id, set())

        # If we have bindings, use index for first binding
        if bindings:
            for role_name, value in bindings.items():
                role_idx = rel_type.role_indices.get(role_name)
                if role_idx is not None:
                    key = (relation_type_id, role_idx, value)
                    indexed_ids = self.tuples_by_role.get(key, set())
                    tuple_ids = tuple_ids & indexed_ids

        # Filter for current tuples and additional bindings
        result = []
        for tid in tuple_ids:
            tup = self.tuples.get(tid)
            if tup is None or not tup.is_current():
                continue

            # Check all bindings
            match = True
            if bindings:
                for role_name, expected_value in bindings.items():
                    role_idx = rel_type.role_indices.get(role_name)
                    if role_idx is not None and tup.values[role_idx] != expected_value:
                        match = False
                        break

            if match:
                result.append(tup)

        return result

    def lookup(self, relation_type_id: int, bindings: Dict[str, Value],
               result_role: str) -> Value:
        """
        Look up a single value from a relation.

        Args:
            relation_type_id: The relation type
            bindings: Partial bindings that should uniquely identify a tuple
            result_role: The role whose value to return

        Returns:
            The value, or Null if no matching tuple
        """
        rel_type = self.relation_types.get(relation_type_id)
        if rel_type is None:
            return Value.null()

        result_idx = rel_type.role_indices.get(result_role)
        if result_idx is None:
            raise ValueError(f"Role '{result_role}' not found in relation")

        tuples = self.query_tuples(relation_type_id, bindings)
        if not tuples:
            return Value.null()

        # Return first match (should be unique for functional relations)
        return tuples[0].values[result_idx]

    # =========================================================================
    # CONSTRAINT OPERATIONS
    # =========================================================================

    def add_constraint(self, name: str, kind: ConstraintKind,
                       check_fn, delta_type_id: Optional[int] = None,
                       derive_fn=None, repair_fn=None,
                       depends_on_relations: Optional[List[int]] = None) -> int:
        """
        Add a constraint.

        Args:
            name: Constraint name
            kind: What kind of constraint
            check_fn: A callable (graph, context) -> bool for checking
            delta_type_id: For preconditions/postconditions, which delta type
            derive_fn: For DERIVED, callable (graph, dirty_relations) -> List[PendingDelta]
            repair_fn: For MAINTENANCE, callable (graph) -> List[PendingDelta]
            depends_on_relations: Which relation types this constraint reads from

        Returns:
            The constraint entity's ID
        """
        entity_id = self.create_entity(PrimordialIds.CONSTRAINT_TYPE, name, level=1)

        constraint = Constraint(
            entity_id=entity_id,
            name=name,
            kind=kind,
            check_fn=check_fn,
            delta_type_id=delta_type_id,
            derive_fn=derive_fn,
            repair_fn=repair_fn,
            depends_on_relations=depends_on_relations or []
        )
        self.constraints[entity_id] = constraint

        if kind == ConstraintKind.INVARIANT:
            self.invariants.append(entity_id)
        elif kind == ConstraintKind.PRECONDITION and delta_type_id is not None:
            if delta_type_id not in self.preconditions:
                self.preconditions[delta_type_id] = []
            self.preconditions[delta_type_id].append(entity_id)
        elif kind == ConstraintKind.POSTCONDITION and delta_type_id is not None:
            if delta_type_id not in self.postconditions:
                self.postconditions[delta_type_id] = []
            self.postconditions[delta_type_id].append(entity_id)

        return entity_id

    def check_invariants(self) -> List[PyTuple[int, str]]:
        """
        Check all invariants.

        Returns:
            List of (constraint_id, error_message) for violations
        """
        violations = []
        for constraint_id in self.invariants:
            constraint = self.constraints[constraint_id]
            try:
                if not constraint.check_fn(self, {}):
                    violations.append((constraint_id, f"Invariant '{constraint.name}' violated"))
            except Exception as e:
                violations.append((constraint_id, f"Invariant '{constraint.name}' error: {e}"))
        return violations

    # =========================================================================
    # EXECUTION / RESOLUTION
    # =========================================================================

    def _topological_sort_pending(self) -> List[PendingDelta]:
        """
        Sort pending deltas by causal dependencies and priority.

        Returns deltas in order such that dependencies come before dependents.
        Within each dependency group, higher priority comes first.
        """
        if not self.pending_deltas:
            return []

        # Build a map of delta index -> pending delta for reference
        # We use list indices since PendingDelta doesn't have an ID yet
        n = len(self.pending_deltas)

        # Check if any deltas have causal dependencies
        has_deps = any(d.causal_deps for d in self.pending_deltas)

        if not has_deps:
            # Simple case: just sort by priority (descending) and source
            source_priority = {
                DeltaSource.EXTERNAL: 4,
                DeltaSource.CONSTRAINT: 3,
                DeltaSource.GOAL: 2,
                DeltaSource.DERIVED: 1
            }
            return sorted(
                self.pending_deltas,
                key=lambda d: (-d.priority, -source_priority.get(d.source, 0)),
                reverse=False
            )

        # Complex case: topological sort with priority tie-breaking
        # Note: causal_deps reference Delta IDs (already applied), not pending indices
        # For now, we treat all pending deltas as independent since they don't
        # reference each other (causal_deps are for provenance tracking)
        source_priority = {
            DeltaSource.EXTERNAL: 4,
            DeltaSource.CONSTRAINT: 3,
            DeltaSource.GOAL: 2,
            DeltaSource.DERIVED: 1
        }
        return sorted(
            self.pending_deltas,
            key=lambda d: (-d.priority, -source_priority.get(d.source, 0)),
            reverse=False
        )

    def _check_preconditions(self, pending: PendingDelta) -> List[ConstraintViolation]:
        """Check preconditions for a pending delta."""
        violations = []

        # Get preconditions for this relation type
        precond_ids = self.preconditions.get(pending.relation_type_id, [])

        for constraint_id in precond_ids:
            constraint = self.constraints.get(constraint_id)
            if constraint is None:
                continue

            # Build context with pending delta info
            rel_type = self.relation_types.get(pending.relation_type_id)
            context = {}
            if rel_type:
                for i, role in enumerate(rel_type.roles):
                    context[role.name] = pending.values[i]

            try:
                if not constraint.check_fn(self, context):
                    violations.append(ConstraintViolation(
                        constraint_id=constraint_id,
                        constraint_name=constraint.name,
                        message=f"Precondition '{constraint.name}' failed",
                        failed_bindings=context
                    ))
            except Exception as e:
                violations.append(ConstraintViolation(
                    constraint_id=constraint_id,
                    constraint_name=constraint.name,
                    message=f"Precondition '{constraint.name}' error: {e}",
                    failed_bindings=context
                ))

        return violations

    def _apply_single_pending(self, pending: PendingDelta) -> Optional[Delta]:
        """
        Apply a single pending delta, creating the actual Delta record.

        Returns the created Delta, or None if application failed.
        """
        rel_type = self.relation_types.get(pending.relation_type_id)
        if rel_type is None:
            return None

        if pending.kind == DeltaKind.ASSERT:
            # Type check
            try:
                self._type_check_tuple(rel_type, pending.values)
            except (ValueError, TypeError) as e:
                return None

            # Create tuple
            tuple_id = self.next_tuple_id
            self.next_tuple_id += 1

            tup = Tuple(
                id=tuple_id,
                type_id=pending.relation_type_id,
                values=pending.values,
                valid_from=self.current_tick,
                valid_to=None
            )
            self.tuples[tuple_id] = tup
            self._index_tuple(tup, add=True)

            # Create delta record
            delta = Delta(
                id=self.next_delta_id,
                kind=DeltaKind.ASSERT,
                tuple_id=tuple_id,
                relation_type_id=pending.relation_type_id,
                values=pending.values,
                old_values=None,
                tick=self.current_tick,
                micro=self.current_micro,
                provenance=pending.provenance or Provenance(cause='external')
            )

        elif pending.kind == DeltaKind.RETRACT:
            if pending.tuple_id is None:
                return None

            tup = self.tuples.get(pending.tuple_id)
            if tup is None or not tup.is_current():
                return None

            # Mark as retracted
            tup.valid_to = self.current_tick
            self._index_tuple(tup, add=False)

            # Create delta record
            delta = Delta(
                id=self.next_delta_id,
                kind=DeltaKind.RETRACT,
                tuple_id=pending.tuple_id,
                relation_type_id=pending.relation_type_id,
                values=pending.values,
                old_values=pending.values,
                tick=self.current_tick,
                micro=self.current_micro,
                provenance=pending.provenance or Provenance(cause='external')
            )

        else:
            # MODIFY not yet implemented
            return None

        self.next_delta_id += 1
        self.current_micro += 1
        self.deltas.append(delta)
        self.recently_applied.append(delta)

        return delta

    def _get_affected_invariants(self, delta: Delta) -> List[int]:
        """
        Get invariants that might be affected by a delta.

        For now, returns all invariants. A full implementation would
        track which constraints depend on which relation types.
        """
        # TODO: Implement dependency tracking for incremental checking
        return list(self.invariants)

    def apply_pending_deltas(self) -> PyTuple[List[int], List[ConstraintViolation]]:
        """
        Phase 1 of resolution: Apply all pending deltas.

        Returns:
            Tuple of (applied_delta_ids, violations)
        """
        if not self.pending_deltas:
            return [], []

        applied = []
        violations = []

        # Sort by dependencies and priority
        ordered = self._topological_sort_pending()

        for pending in ordered:
            # Check preconditions
            precond_violations = self._check_preconditions(pending)

            if precond_violations:
                if pending.violation_policy == ViolationPolicy.REJECT:
                    violations.extend(precond_violations)
                    continue  # Skip this delta
                # APPLY_AND_REPAIR would continue anyway

            # Apply the delta
            delta = self._apply_single_pending(pending)

            if delta is None:
                continue

            applied.append(delta.id)

            # Check postconditions
            postcond_ids = self.postconditions.get(pending.relation_type_id, [])
            for constraint_id in postcond_ids:
                constraint = self.constraints.get(constraint_id)
                if constraint is None:
                    continue

                try:
                    if not constraint.check_fn(self, {}):
                        violations.append(ConstraintViolation(
                            constraint_id=constraint_id,
                            constraint_name=constraint.name,
                            message=f"Postcondition '{constraint.name}' violated",
                            trigger_delta_id=delta.id
                        ))
                except Exception as e:
                    violations.append(ConstraintViolation(
                        constraint_id=constraint_id,
                        constraint_name=constraint.name,
                        message=f"Postcondition error: {e}",
                        trigger_delta_id=delta.id
                    ))

            # Check affected invariants
            affected = self._get_affected_invariants(delta)
            for constraint_id in affected:
                constraint = self.constraints.get(constraint_id)
                if constraint is None:
                    continue

                try:
                    if not constraint.check_fn(self, {}):
                        violations.append(ConstraintViolation(
                            constraint_id=constraint_id,
                            constraint_name=constraint.name,
                            message=f"Invariant '{constraint.name}' violated",
                            trigger_delta_id=delta.id
                        ))
                except Exception as e:
                    violations.append(ConstraintViolation(
                        constraint_id=constraint_id,
                        constraint_name=constraint.name,
                        message=f"Invariant error: {e}",
                        trigger_delta_id=delta.id
                    ))

        # Clear pending deltas
        self.pending_deltas.clear()

        return applied, violations

    def propagate_constraints(self) -> int:
        """
        Phase 2 of resolution: Propagate constraint consequences.

        This handles:
        - DERIVED constraints: compute new values from other relations
        - MAINTENANCE constraints: generate repair deltas when conditions become false

        Returns:
            Number of new deltas generated
        """
        if not self.recently_applied:
            return 0

        # Find which relation types changed
        dirty_relations: Set[int] = set()
        for delta in self.recently_applied:
            dirty_relations.add(delta.relation_type_id)

        # Clear recently applied (we've processed them)
        self.recently_applied.clear()

        new_deltas_count = 0

        # Process derived constraints
        for constraint_id, constraint in self.constraints.items():
            if constraint.kind != ConstraintKind.DERIVED:
                continue
            if constraint.derive_fn is None:
                continue

            # Check if any dependency is dirty
            deps = constraint.depends_on_relations
            if deps and not any(d in dirty_relations for d in deps):
                continue

            # Generate derived deltas
            try:
                new_deltas = constraint.derive_fn(self, dirty_relations)
                if new_deltas:
                    for pd in new_deltas:
                        pd.source = DeltaSource.DERIVED
                        pd.source_constraint_id = constraint_id
                        self.pending_deltas.append(pd)
                        new_deltas_count += 1
            except Exception as e:
                # Log but continue
                pass

        # Process maintenance constraints
        for constraint_id, constraint in self.constraints.items():
            if constraint.kind != ConstraintKind.MAINTENANCE:
                continue

            # Check if condition is violated
            if constraint.check_fn is not None:
                try:
                    condition_holds = constraint.check_fn(self, {})
                except Exception:
                    condition_holds = True  # Assume OK on error

                if condition_holds:
                    continue  # No repair needed

            # Generate repair deltas
            if constraint.repair_fn is not None:
                try:
                    repair_deltas = constraint.repair_fn(self)
                    if repair_deltas:
                        for pd in repair_deltas:
                            pd.source = DeltaSource.CONSTRAINT
                            pd.source_constraint_id = constraint_id
                            self.pending_deltas.append(pd)
                            new_deltas_count += 1
                except Exception as e:
                    # Log but continue
                    pass

        return new_deltas_count

    def resolve(self, max_iterations: int = 1000) -> ResolutionResult:
        """
        The main resolution loop.

        Runs until the graph reaches a quiescent state (no more pending work)
        or hits the iteration limit.

        Args:
            max_iterations: Safety limit to prevent infinite loops

        Returns:
            ResolutionResult with status and diagnostics
        """
        all_applied = []
        all_violations = []
        propagation_cycles = 0

        for iteration in range(max_iterations):
            # Phase 1: Apply pending deltas
            applied, violations = self.apply_pending_deltas()
            all_applied.extend(applied)
            all_violations.extend(violations)

            # Phase 2: Propagate constraint consequences
            new_deltas = self.propagate_constraints()
            if new_deltas > 0:
                propagation_cycles += 1

            # Phase 3: Pursue active goals (not yet implemented)
            # goal_deltas = self.pursue_goals()

            # Phase 4: Check for quiescence
            if not self.pending_deltas and new_deltas == 0:
                # We've reached a stable state
                status = ResolutionStatus.QUIESCENT
                if all_violations:
                    status = ResolutionStatus.CONSTRAINT_VIOLATIONS

                return ResolutionResult(
                    status=status,
                    iterations=iteration + 1,
                    applied_deltas=all_applied,
                    rejected_deltas=[],  # TODO: track rejected
                    violations=all_violations,
                    propagation_cycles=propagation_cycles
                )

        # Hit iteration limit
        return ResolutionResult(
            status=ResolutionStatus.DIVERGED,
            iterations=max_iterations,
            applied_deltas=all_applied,
            rejected_deltas=[],
            violations=all_violations,
            propagation_cycles=propagation_cycles
        )

    def tick_with_resolve(self, external_inputs: Optional[List[Dict]] = None):
        """
        Advance one tick using the resolution loop.

        This is the recommended way to run game ticks in v2:
        1. Queue external inputs as pending deltas
        2. Resolve until quiescent
        3. Advance time

        Args:
            external_inputs: List of dicts with keys:
                - relation_type_id: int
                - bindings: Dict[str, Value]
                - kind: DeltaKind (default ASSERT)
        """
        # Queue external inputs
        if external_inputs:
            for inp in external_inputs:
                kind = inp.get('kind', DeltaKind.ASSERT)
                self.queue_delta(
                    kind=kind,
                    relation_type_id=inp['relation_type_id'],
                    bindings=inp['bindings'],
                    tuple_id=inp.get('tuple_id'),
                    source=DeltaSource.EXTERNAL,
                    priority=100  # External inputs are high priority
                )

        # Resolve
        result = self.resolve()

        if result.status == ResolutionStatus.DIVERGED:
            raise RuntimeError(f"Resolution diverged at tick {self.current_tick}")

        if result.violations:
            # Log violations but continue
            for v in result.violations:
                print(f"Warning: {v.message}")

        # Advance time
        self.current_tick += 1
        self.current_micro = 0

        return result

    def tick(self):
        """
        Advance to the next tick.

        This is the basic execution step for game-like scenarios.
        For event-driven systems, use resolve() directly.
        """
        # Check invariants
        violations = self.check_invariants()
        if violations:
            print(f"Warning: {len(violations)} invariant violations at tick {self.current_tick}")
            for cid, msg in violations:
                print(f"  - {msg}")

        # Advance time
        self.current_tick += 1
        self.current_micro = 0

    # =========================================================================
    # PROVENANCE
    # =========================================================================

    def why(self, tuple_id: int) -> List[Delta]:
        """
        Get the provenance chain for a tuple.

        Returns:
            List of deltas that led to this tuple's current state
        """
        result = []
        for delta in self.deltas:
            if delta.tuple_id == tuple_id:
                result.append(delta)
        return result

    # =========================================================================
    # VIEWS (TEXT RENDERING)
    # =========================================================================

    def render_entity(self, entity_id: int) -> str:
        """Render an entity as text."""
        entity = self.entities.get(entity_id)
        if entity is None:
            return f"<unknown entity {entity_id}>"

        name = self.name_by_entity.get(entity_id, f"#{entity_id}")
        type_name = self.name_by_entity.get(entity.type_id, f"#{entity.type_id}")
        return f"{name} : {type_name}"

    def render_tuple(self, tuple_id: int) -> str:
        """Render a tuple as text."""
        tup = self.tuples.get(tuple_id)
        if tup is None:
            return f"<unknown tuple {tuple_id}>"

        rel_type = self.relation_types.get(tup.type_id)
        if rel_type is None:
            return f"<tuple {tuple_id} of unknown type>"

        parts = []
        for role, value in zip(rel_type.roles, tup.values):
            if value.type == ValueType.ENTITY_REF:
                value_str = self.name_by_entity.get(value.data, f"@{value.data}")
            else:
                value_str = repr(value)
            parts.append(f"{role.name}: {value_str}")

        status = "" if tup.is_current() else " [retracted]"
        return f"{rel_type.name}({', '.join(parts)}){status}"

    def dump(self):
        """Print a summary of the graph state."""
        print(f"=== HERB Graph (tick {self.current_tick}) ===")
        print(f"Entities: {len(self.entities)}")
        print(f"Tuples: {len([t for t in self.tuples.values() if t.is_current()])}")
        print(f"Deltas: {len(self.deltas)}")
        print(f"Constraints: {len(self.constraints)}")

        print("\n--- Entity Types (user-defined) ---")
        for eid, entity in self.entities.items():
            if eid >= PrimordialIds.FIRST_USER_ID and entity.type_id == PrimordialIds.ENTITY_TYPE:
                print(f"  {self.render_entity(eid)}")

        print("\n--- Relation Types (user-defined) ---")
        for eid, rel_type in self.relation_types.items():
            if eid >= PrimordialIds.FIRST_USER_ID:
                roles_str = ", ".join(f"{r.name}: {r.value_type.name}" for r in rel_type.roles)
                print(f"  {rel_type.name}({roles_str})")

        print("\n--- Current Tuples ---")
        for tid, tup in self.tuples.items():
            if tup.is_current():
                print(f"  {self.render_tuple(tid)}")


# =============================================================================
# DEMONSTRATION
# =============================================================================

def demo():
    """Demonstrate basic graph operations."""
    print("Creating HERB v2 graph...\n")

    g = Graph()

    # Define entity types
    print("Defining entity types...")
    player_type = g.define_entity_type("player")
    resource_type = g.define_entity_type("resource")

    # Define relation types
    print("Defining relation types...")
    holds = g.define_relation_type("holds", [
        ("holder", ValueType.ENTITY_REF, player_type),
        ("resource", ValueType.ENTITY_REF, resource_type),
        ("amount", ValueType.INT, None)
    ])

    # Create instances
    print("Creating instances...")
    player_1 = g.create_entity(player_type, "player_1")
    gold = g.create_entity(resource_type, "gold")

    # Assert a tuple
    print("Asserting tuple...")
    holds_tuple = g.assert_tuple(holds, {
        "holder": Value.entity_ref(player_1),
        "resource": Value.entity_ref(gold),
        "amount": Value.int(200)
    })

    # Add an invariant
    print("Adding invariant...")
    def gold_nonnegative(graph, ctx):
        # Check all holds tuples have non-negative amount
        for tup in graph.query_tuples(holds):
            amount = tup.values[2]  # amount is third role
            if amount.type == ValueType.INT and amount.data < 0:
                return False
        return True

    g.add_constraint("gold_nonnegative", ConstraintKind.INVARIANT, gold_nonnegative)

    # Query
    print("\nQuerying holds tuples...")
    results = g.query_tuples(holds)
    for tup in results:
        print(f"  {g.render_tuple(tup.id)}")

    # Lookup
    print("\nLooking up player_1's gold...")
    amount = g.lookup(holds, {
        "holder": Value.entity_ref(player_1),
        "resource": Value.entity_ref(gold)
    }, "amount")
    print(f"  Amount: {amount}")

    # Dump state
    print()
    g.dump()

    # Provenance
    print("\n--- Provenance for holds tuple ---")
    for delta in g.why(holds_tuple):
        print(f"  {delta.kind.name} at tick {delta.tick}: {delta.provenance.cause}")

    print("\nDemo complete.")


if __name__ == "__main__":
    demo()
